/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class AWDNFCSERemovedEvent, NSString;

@interface NFAWDSERemoved : NSObject <NFAWDEventProtocol> {
    unsigned int reason;
    AWDNFCSERemovedEvent *_metric;
}

@property unsigned int reason;
@property AWDNFCSERemovedEvent * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)getMetric;
- (unsigned int)getMetricId;
- (id)metric;
- (void)setReason:(unsigned int)arg1;
- (void)setMetric:(id)arg1;
- (unsigned int)reason;
- (id)init;
- (void)dealloc;

@end
