/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSString, AWDNFCTSMAPNReceivedEvent;

@interface NFAWDAPNReceived : NSObject <NFAWDEventProtocol> {
    AWDNFCTSMAPNReceivedEvent *_metric;
}

@property AWDNFCTSMAPNReceivedEvent * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)getMetric;
- (unsigned int)getMetricId;
- (void)updateTSMTransactionStateWithUUID:(id)arg1 withUUIDRefTimestamp:(unsigned long long)arg2;
- (id)metric;
- (void)setMetric:(id)arg1;
- (id)init;
- (void)dealloc;

@end
