/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSString, AWDNFCTSMStartEvent;

@interface NFAWDTSMStart : NSObject <NFAWDEventProtocol> {
    unsigned int memoryTransientDeselect;
    unsigned int memoryTransientReset;
    unsigned int memoryPersistent;
    unsigned int memoryIndexTable;
    NSString *url;
    AWDNFCTSMStartEvent *_metric;
}

@property(retain) NSString * url;
@property unsigned int memoryTransientDeselect;
@property unsigned int memoryTransientReset;
@property unsigned int memoryPersistent;
@property unsigned int memoryIndexTable;
@property AWDNFCTSMStartEvent * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (unsigned int)memoryIndexTable;
- (unsigned int)memoryPersistent;
- (unsigned int)memoryTransientReset;
- (unsigned int)memoryTransientDeselect;
- (void)setMemoryIndexTable:(unsigned int)arg1;
- (void)setMemoryTransientReset:(unsigned int)arg1;
- (void)setMemoryTransientDeselect:(unsigned int)arg1;
- (void)setMemoryPersistent:(unsigned int)arg1;
- (id)getMetric;
- (unsigned int)getMetricId;
- (void)updateTSMTransactionStateWithUUID:(id)arg1 withUUIDRefTimestamp:(unsigned long long)arg2;
- (id)metric;
- (void)setMetric:(id)arg1;
- (void)setUrl:(id)arg1;
- (id)url;
- (id)init;
- (void)dealloc;

@end
