/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSData, AWDNFCSECRSAuthorize, NSString;

@interface NFAWDCRSAuthorize : NSObject <NFAWDEventProtocol> {
    unsigned int status;
    unsigned int method;
    NSData *aid;
    AWDNFCSECRSAuthorize *_metric;
}

@property unsigned int status;
@property unsigned int method;
@property(retain) NSData * aid;
@property AWDNFCSECRSAuthorize * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)getMetric;
- (unsigned int)getMetricId;
- (unsigned long long)updateTransactionStateInfoPreviousState:(unsigned long long)arg1 withUUID:(id)arg2 withUUIDRefTimestamp:(unsigned long long)arg3;
- (id)aid;
- (void)setAid:(id)arg1;
- (id)metric;
- (void)setMethod:(unsigned int)arg1;
- (void)setMetric:(id)arg1;
- (void)setStatus:(unsigned int)arg1;
- (unsigned int)status;
- (unsigned int)method;
- (id)init;
- (void)dealloc;

@end
