/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSData, AWDNFCJCOPRestrictedModeEvent, NSString;

@interface NFAWDRestrictedModeEnter : NSObject <NFAWDEventProtocol> {
    boolcontactlessMode;
    NSData *attackLog;
    AWDNFCJCOPRestrictedModeEvent *_metric;
}

@property bool contactlessMode;
@property(retain) NSData * attackLog;
@property AWDNFCJCOPRestrictedModeEvent * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)attackLog;
- (bool)contactlessMode;
- (void)setAttackLog:(id)arg1;
- (void)setContactlessMode:(bool)arg1;
- (id)getMetric;
- (unsigned int)getMetricId;
- (id)metric;
- (void)setMetric:(id)arg1;
- (id)init;
- (void)dealloc;

@end
