/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSData, NSString, AWDNFCHCIEndOfTransactionEvent;

@interface NFAWDEndOfTransaction : NSObject <NFAWDEventProtocol> {
    unsigned int version;
    unsigned int status;
    unsigned int command;
    unsigned int transactionStatus;
    unsigned int informative;
    unsigned int currencyCode;
    unsigned int mobileCVMResult;
    unsigned int msc;
    NSData *transactionId;
    NSData *aid;
    unsigned long long amount;
    unsigned long long iad;
    NSData *cdi;
    NSData *maid;
    NSData *mcii;
    AWDNFCHCIEndOfTransactionEvent *_metric;
}

@property unsigned int version;
@property unsigned int status;
@property unsigned int command;
@property(retain) NSData * transactionId;
@property unsigned int transactionStatus;
@property unsigned int informative;
@property(retain) NSData * aid;
@property unsigned long long amount;
@property unsigned int currencyCode;
@property unsigned long long iad;
@property unsigned int mobileCVMResult;
@property(retain) NSData * cdi;
@property(retain) NSData * maid;
@property unsigned int msc;
@property(retain) NSData * mcii;
@property AWDNFCHCIEndOfTransactionEvent * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (unsigned int)mobileCVMResult;
- (void)setMobileCVMResult:(unsigned int)arg1;
- (id)getMetric;
- (unsigned int)getMetricId;
- (unsigned long long)updateTransactionStateInfoPreviousState:(unsigned long long)arg1 withUUID:(id)arg2 withUUIDRefTimestamp:(unsigned long long)arg3;
- (id)maid;
- (id)mcii;
- (unsigned int)msc;
- (id)cdi;
- (unsigned long long)iad;
- (unsigned int)informative;
- (unsigned int)transactionStatus;
- (void)setMsc:(unsigned int)arg1;
- (void)setIad:(unsigned long long)arg1;
- (void)setInformative:(unsigned int)arg1;
- (void)setTransactionStatus:(unsigned int)arg1;
- (void)setMaid:(id)arg1;
- (void)setMcii:(id)arg1;
- (void)setCdi:(id)arg1;
- (id)transactionId;
- (void)setTransactionId:(id)arg1;
- (id)aid;
- (void)setAid:(id)arg1;
- (id)metric;
- (void)setMetric:(id)arg1;
- (void)setCurrencyCode:(unsigned int)arg1;
- (unsigned int)currencyCode;
- (void)setCommand:(unsigned int)arg1;
- (void)setStatus:(unsigned int)arg1;
- (unsigned int)status;
- (unsigned long long)amount;
- (void)setAmount:(unsigned long long)arg1;
- (unsigned int)version;
- (void)setVersion:(unsigned int)arg1;
- (id)init;
- (void)dealloc;
- (unsigned int)command;

@end
