/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSString, AWDNFCHardwareExceptionEvent;

@interface NFAWDHardwareException : NSObject <NFAWDEventProtocol> {
    unsigned int type;
    NSString *data;
    AWDNFCHardwareExceptionEvent *_metric;
}

@property unsigned int type;
@property(retain) NSString * data;
@property AWDNFCHardwareExceptionEvent * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)getMetric;
- (unsigned int)getMetricId;
- (id)metric;
- (void)setMetric:(id)arg1;
- (void)setData:(id)arg1;
- (id)data;
- (unsigned int)type;
- (void)setType:(unsigned int)arg1;
- (id)init;
- (void)dealloc;

@end
