/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSString, AWDNFCVersions;

@interface NFAWDVersionInfo : NSObject <NFAWDEventProtocol> {
    unsigned int nfccHWVersion;
    unsigned int nfccROMVersion;
    unsigned int nfccFWVersion;
    unsigned int nfccFWRevision;
    unsigned int nfccMWVersion;
    unsigned int seDeviceType;
    unsigned int seHWVersion;
    unsigned int seFWVersion;
    unsigned int seSignKeyType;
    unsigned int seSeqCount;
    unsigned int seRefCount;
    unsigned int seRestrictedMode;
    unsigned int seOSMode;
    unsigned int seMigrationState;
    unsigned int seMigrationPkgs;
    unsigned int seMigrationInst;
    NSString *sePlatformId;
    AWDNFCVersions *_metric;
}

@property unsigned int nfccHWVersion;
@property unsigned int nfccROMVersion;
@property unsigned int nfccFWVersion;
@property unsigned int nfccFWRevision;
@property unsigned int nfccMWVersion;
@property(retain) NSString * sePlatformId;
@property unsigned int seDeviceType;
@property unsigned int seHWVersion;
@property unsigned int seFWVersion;
@property unsigned int seSignKeyType;
@property unsigned int seSeqCount;
@property unsigned int seRefCount;
@property unsigned int seOSMode;
@property unsigned int seRestrictedMode;
@property unsigned int seMigrationState;
@property unsigned int seMigrationPkgs;
@property unsigned int seMigrationInst;
@property AWDNFCVersions * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (unsigned int)seRefCount;
- (unsigned int)seSeqCount;
- (id)sePlatformId;
- (unsigned int)nfccMWVersion;
- (void)setSePlatformId:(id)arg1;
- (void)setSeRefCount:(unsigned int)arg1;
- (void)setSeSeqCount:(unsigned int)arg1;
- (void)setNfccMWVersion:(unsigned int)arg1;
- (id)getMetric;
- (unsigned int)getMetricId;
- (unsigned int)seMigrationInst;
- (unsigned int)seMigrationPkgs;
- (unsigned int)seMigrationState;
- (unsigned int)seRestrictedMode;
- (unsigned int)seOSMode;
- (unsigned int)seSignKeyType;
- (unsigned int)seFWVersion;
- (unsigned int)seHWVersion;
- (unsigned int)seDeviceType;
- (unsigned int)nfccFWRevision;
- (unsigned int)nfccFWVersion;
- (unsigned int)nfccROMVersion;
- (unsigned int)nfccHWVersion;
- (void)setSeMigrationInst:(unsigned int)arg1;
- (void)setSeMigrationPkgs:(unsigned int)arg1;
- (void)setSeMigrationState:(unsigned int)arg1;
- (void)setSeRestrictedMode:(unsigned int)arg1;
- (void)setSeOSMode:(unsigned int)arg1;
- (void)setSeSignKeyType:(unsigned int)arg1;
- (void)setSeFWVersion:(unsigned int)arg1;
- (void)setSeHWVersion:(unsigned int)arg1;
- (void)setSeDeviceType:(unsigned int)arg1;
- (void)setNfccFWRevision:(unsigned int)arg1;
- (void)setNfccFWVersion:(unsigned int)arg1;
- (void)setNfccROMVersion:(unsigned int)arg1;
- (void)setNfccHWVersion:(unsigned int)arg1;
- (id)metric;
- (void)setMetric:(id)arg1;
- (id)init;
- (void)dealloc;

@end
