/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSString, AWDNFCTSMConnectivityExceptionEvent;

@interface NFAWDTSMConnectivityException : NSObject <NFAWDEventProtocol> {
    unsigned int errorCode;
    AWDNFCTSMConnectivityExceptionEvent *_metric;
}

@property unsigned int errorCode;
@property AWDNFCTSMConnectivityExceptionEvent * metric;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)getMetric;
- (unsigned int)getMetricId;
- (unsigned long long)updateTransactionStateInfoPreviousState:(unsigned long long)arg1 withUUID:(id)arg2 withUUIDRefTimestamp:(unsigned long long)arg3;
- (id)metric;
- (void)setMetric:(id)arg1;
- (void)setErrorCode:(unsigned int)arg1;
- (unsigned int)errorCode;
- (id)init;
- (void)dealloc;

@end
