/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NSString;

@interface NFCard : NSObject  {
    unsigned char _family;
    unsigned char _lifecycleState;
    unsigned char _activationState;
    bool_authTransientSupport;
    NSString *_aid;
}

@property(readonly) NSString * aid;
@property(readonly) unsigned char family;
@property(readonly) unsigned char lifecycleState;
@property(readonly) unsigned char activationState;
@property(readonly) bool authTransientSupport;


- (id)aid;
- (unsigned char)lifecycleState;
- (unsigned char)activationState;
- (unsigned char)family;
- (bool)authTransientSupport;
- (void)setIsActive:(bool)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)description;
- (void)dealloc;

@end
