/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NFCardManagerEventListener, NFCardManagerInternal, NSString, NSObject<OS_dispatch_queue>, <NFCardManagerDelegate>;

@interface NFCardManager : NSObject <NFCardManagerEventListenerDelegate> {
    NFCardManagerInternal *_cm;
    NFCardManagerEventListener *_evtListener;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    NSObject<OS_dispatch_queue> *_workQueue;
    <NFCardManagerDelegate> *_delegate;
}

@property <NFCardManagerDelegate> * delegate;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)certificates:(id)arg1;
- (void)queueServerConnection:(id)arg1;
- (void)activateOnlyCardWithAID:(id)arg1 callback:(id)arg2;
- (void)setAuthentication:(id)arg1 callback:(id)arg2;
- (void)signChallenge:(id)arg1 callback:(id)arg2;
- (void)serverRegistrationInfo:(id)arg1 callback:(id)arg2;
- (void)setupNewUser:(id)arg1;
- (void)deleteAllCards:(id)arg1;
- (void)deleteCardsWithAIDs:(id)arg1 callback:(id)arg2;
- (void)deauthorizeContactlessPaymentWithCallback:(id)arg1;
- (void)authorizeContactlessPaymentWithAuthToken:(id)arg1 callback:(id)arg2;
- (void)setPaymentCardWithAID:(id)arg1 callback:(id)arg2;
- (void)deactivateCardsWithAIDs:(id)arg1 callback:(id)arg2;
- (void)activateCardsWithAIDs:(id)arg1 callback:(id)arg2;
- (void)cardWithAID:(id)arg1 callback:(id)arg2;
- (void)authorizeEcommerceTransaction:(id)arg1 authorization:(id)arg2 callback:(id)arg3;
- (void)activateOnlyCardWithAID:(id)arg1 authorization:(id)arg2 callback:(id)arg3;
- (unsigned int)isInRestrictedMode;
- (void)serverRegistrationInfo:(id)arg1;
- (void)installedAIDs:(id)arg1;
- (void)serialNumber:(id)arg1;
- (void)stopEventListener;
- (bool)startEventListener;
- (id)initWithDelegate:(id)arg1 queue:(id)arg2 idleExit:(bool)arg3;
- (void)cardManagerEventListener:(id)arg1 secureElementDidBecomeAvailable:(bool)arg2;
- (void)cardManagerEventListener:(id)arg1 didReceiveRemoteAdminNotification:(id)arg2;
- (id)initWithQueue:(id)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end
