/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class XPCConnection, NSString, NSObject<OS_dispatch_queue>, <NFCardManagerEventListenerDelegate>;

@interface NFCardManagerEventListener : NSObject <XPCConnectionDelegate> {
    bool_idleExit;
    bool_isRegistered;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    XPCConnection *_xpcConnection;
    <NFCardManagerEventListenerDelegate> *_delegate;
}

@property <NFCardManagerEventListenerDelegate> * delegate;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)stopEventListener;
- (bool)startEventListener;
- (id)initWithDelegate:(id)arg1 queue:(id)arg2 idleExit:(bool)arg3;
- (void)_handleUEAEvent:(id)arg1;
- (void)XPCConnectionServiceDidRestart:(id)arg1;
- (void)XPCConnection:(id)arg1 didReceiveEvent:(id)arg2;
- (void)XPCConnectionDidTerminate:(id)arg1;
- (id)_getXPCConnection;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end
