/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@interface NFCardEmulationUEA : NFCardEmulation  {
}


- (void)_stopFieldDetect;
- (void)_startFieldDetect;
- (void)_stopCardEmulation;
- (void)_startCardEmulation;
- (void)_handleEvent:(id)arg1;

@end
