/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@interface NFCurrency : NSObject  {
}

+ (int)getFractionDigitsFromCurrencyStringCode:(id)arg1;
+ (id)getCurrencyStringCodeFromNumericCode:(unsigned int)arg1;
+ (id)encodeBCDAmount:(unsigned long long)arg1;
+ (unsigned long long)decodeBCDAmount:(id)arg1;


@end
