/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class XPCConnection, NSString;

@interface NFDaemonProxy : NSObject <XPCConnectionDelegate> {
    XPCConnection *_xpc;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (id)sharedDaemonProxy;

- (unsigned int)sendBoosterCommand:(id)arg1;
- (unsigned int)readBoosterRegister:(unsigned char)arg1 value:(char *)arg2;
- (void)XPCConnectionServiceDidRestart:(id)arg1;
- (void)XPCConnection:(id)arg1 didReceiveEvent:(id)arg2;
- (void)XPCConnectionDidTerminate:(id)arg1;
- (id)_getXPCConnection;
- (unsigned int)getBoosterInfo:(id*)arg1;
- (unsigned int)getSecureElementInfo:(id*)arg1;
- (unsigned int)getControllerInfo:(id*)arg1;
- (void)dealloc;

@end
