/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NSDecimalNumber, NSString, NSData, NSDate;

@interface NFECommerceTransactionRequest : NSObject  {
    unsigned char _merchantCapabilities;
    unsigned int _unpredictableNumber;
    NSString *_applicationIdentifier;
    NSData *_merchantData;
    NSString *_merchantIdentifier;
    NSString *_currencyCode;
    NSString *_countryCode;
    NSDecimalNumber *_transactionAmount;
    NSDate *_transactionDate;
}

@property(retain) NSString * applicationIdentifier;
@property(retain) NSData * merchantData;
@property(retain) NSString * merchantIdentifier;
@property(retain) NSString * currencyCode;
@property(retain) NSString * countryCode;
@property(retain) NSDecimalNumber * transactionAmount;
@property(retain) NSDate * transactionDate;
@property unsigned char merchantCapabilities;
@property unsigned int unpredictableNumber;

+ (id)getCountryCodeTranslationTable;

- (unsigned char)merchantCapabilities;
- (void)setMerchantCapabilities:(unsigned char)arg1;
- (id)countryCode;
- (void)setCountryCode:(id)arg1;
- (void)setUnpredictableNumber:(unsigned int)arg1;
- (void)setTransactionAmount:(id)arg1;
- (void)setMerchantData:(id)arg1;
- (void)setMerchantIdentifier:(id)arg1;
- (id)merchantIdentifier;
- (void)setCurrencyCode:(id)arg1;
- (id)currencyCode;
- (unsigned int)unpredictableNumber;
- (bool)currencyValueConversion:(id)arg1 output:(char *)arg2 maxLen:(int)arg3 fractionDigit:(int)arg4;
- (id)merchantData;
- (void)setApplicationIdentifier:(id)arg1;
- (id)asDictionary;
- (id)applicationIdentifier;
- (void)dealloc;
- (id)transactionAmount;
- (void)setTransactionDate:(id)arg1;
- (id)transactionDate;

@end
