/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NSString, NSData;

@interface NFEcommerceTransactionResponse : NSObject  {
    NSString *_transactionIdentifier;
    NSData *_transactionData;
}

@property(readonly) NSString * transactionIdentifier;
@property(readonly) NSData * transactionData;

+ (id)responseWithInfo:(id)arg1;

- (id)transactionIdentifier;
- (id)transactionData;
- (void)dealloc;

@end
