/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@interface NFHardwareControllerInfo : NSObject  {
    unsigned long long _siliconVersion;
    unsigned long long _ROMVersion;
    unsigned long long _firmwareVersion;
    unsigned long long _firmwareRevision;
    unsigned long long _middlewareVersion;
}

@property(readonly) unsigned long long siliconVersion;
@property(readonly) unsigned long long ROMVersion;
@property(readonly) unsigned long long firmwareVersion;
@property(readonly) unsigned long long firmwareRevision;
@property(readonly) unsigned long long middlewareVersion;


- (unsigned long long)middlewareVersion;
- (unsigned long long)firmwareVersion;
- (unsigned long long)ROMVersion;
- (unsigned long long)siliconVersion;
- (id)initWithDictionary:(id)arg1;
- (unsigned long long)firmwareRevision;

@end
