/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NSString;

@interface NFHardwareSecureElementInfo : NSObject  {
    bool_restrictedMode;
    unsigned long long _OSVersion;
    unsigned long long _firmwareVersion;
    unsigned long long _hardwareVersion;
    unsigned long long _deviceType;
    unsigned long long _sequenceCounter;
    unsigned long long _referenceCounter;
    unsigned long long _osid;
    unsigned long long _otherOSValid;
    unsigned long long _OSMode;
    unsigned long long _signingKeyType;
    unsigned long long _migrationState;
    unsigned long long _migrationPackages;
    unsigned long long _migrationInstances;
    NSString *_platformIdentifier;
    NSString *_serialNumber;
}

@property(readonly) unsigned long long OSVersion;
@property(readonly) unsigned long long firmwareVersion;
@property(readonly) unsigned long long hardwareVersion;
@property(readonly) unsigned long long deviceType;
@property(readonly) unsigned long long sequenceCounter;
@property(readonly) unsigned long long referenceCounter;
@property(readonly) unsigned long long osid;
@property(readonly) unsigned long long otherOSValid;
@property(readonly) bool restrictedMode;
@property(readonly) unsigned long long OSMode;
@property(readonly) unsigned long long signingKeyType;
@property(readonly) unsigned long long migrationState;
@property(readonly) unsigned long long migrationPackages;
@property(readonly) unsigned long long migrationInstances;
@property(readonly) NSString * platformIdentifier;
@property(readonly) NSString * serialNumber;


- (unsigned long long)hardwareVersion;
- (unsigned long long)deviceType;
- (unsigned long long)signingKeyType;
- (id)platformIdentifier;
- (unsigned long long)migrationInstances;
- (unsigned long long)migrationPackages;
- (unsigned long long)migrationState;
- (unsigned long long)OSMode;
- (bool)restrictedMode;
- (unsigned long long)otherOSValid;
- (unsigned long long)osid;
- (unsigned long long)referenceCounter;
- (unsigned long long)sequenceCounter;
- (unsigned long long)firmwareVersion;
- (unsigned long long)OSVersion;
- (id)serialNumber;
- (id)initWithDictionary:(id)arg1;
- (void)dealloc;

@end
