/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NSData;

@interface NFHardwareBoosterInfo : NSObject  {
    unsigned long long _siliconVersion;
    NSData *_staticConfig;
    NSData *_dynamicConfig;
}

@property(readonly) unsigned long long siliconVersion;
@property(readonly) NSData * staticConfig;
@property(readonly) NSData * dynamicConfig;


- (id)dynamicConfig;
- (id)staticConfig;
- (unsigned long long)siliconVersion;
- (id)initWithDictionary:(id)arg1;
- (void)dealloc;

@end
