/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSObject<OS_dispatch_queue>;

@interface NFTimer : NSObject  {
    unsigned int _index;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _block;

    NSObject<OS_dispatch_queue> *_queue;
}


- (void)startTimer:(double)arg1;
- (id)initWithCallback:(id)arg1 queue:(id)arg2;
- (void)dealloc;
- (void)stopTimer;

@end
