/* Generated by RuntimeBrowser.
   Image: /usr/lib/libnfshared.dylib
 */

@class NSData, NSArray;

@interface NFTLV : NSObject  {
    unsigned int _tag;
    NSData *_value;
    NSArray *_children;
}

@property(readonly) unsigned int tag;
@property(readonly) NSData * value;
@property(readonly) NSArray * children;

+ (id)TLVWithData:(id)arg1;
+ (id)TLVWithTag:(unsigned int)arg1 children:(id)arg2;
+ (id)TLVWithTag:(unsigned int)arg1 value:(id)arg2;
+ (id)_intToData:(unsigned int)arg1;
+ (id)TLVsWithData:(id)arg1;
+ (id)_parseTLVs:(const char **)arg1 end:(const char *)arg2;

- (id)childWithTag:(unsigned int)arg1;
- (id)childrenWithTag:(unsigned int)arg1;
- (unsigned long long)valueAsUnsignedLongLong;
- (unsigned int)valueAsUnsignedLong;
- (id)valueAsString;
- (id)asData;
- (id)children;
- (unsigned int)tag;
- (id)value;
- (id)description;
- (void)dealloc;

@end
