/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NSString, NSDecimalNumber, NSData;

@interface NFTransactionEndEvent : NSObject  {
    unsigned short _command;
    unsigned short _status;
    unsigned short _result;
    unsigned short _informative;
    NSString *_aid;
    NSString *_transactionId;
    NSDecimalNumber *_amount;
    NSString *_currency;
    NSData *_tlv;
}

@property(readonly) NSString * aid;
@property(readonly) NSString * transactionId;
@property(readonly) unsigned short command;
@property(readonly) unsigned short status;
@property(readonly) unsigned short result;
@property(readonly) unsigned short informative;
@property(readonly) NSDecimalNumber * amount;
@property(readonly) NSString * currency;
@property(readonly) NSData * tlv;


- (unsigned short)informative;
- (id)transactionId;
- (id)aid;
- (id)currency;
- (id)tlv;
- (unsigned short)status;
- (unsigned short)result;
- (id)amount;
- (id)initWithDictionary:(id)arg1;
- (id)description;
- (void)dealloc;
- (unsigned short)command;

@end
