/* Generated by RuntimeBrowser.
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@class NSString;

@interface NFTransactionStartEvent : NSObject  {
    unsigned short _status;
    NSString *_aid;
}

@property(readonly) NSString * aid;
@property(readonly) unsigned short status;


- (id)transactionId;
- (id)aid;
- (unsigned short)status;
- (id)initWithDictionary:(id)arg1;
- (id)description;
- (void)dealloc;

@end
